// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace TerapijaCovidaa.Migrations
{
    [DbContext(typeof(ProjekatContext))]
    [Migration("20220321092131_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Models.KartonPacijenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AmbulantaId")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LBO")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("AmbulantaId");

                    b.ToTable("Kartoni");
                });

            modelBuilder.Entity("Models.KovidAmbulanta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Ambulante");
                });

            modelBuilder.Entity("Models.Lek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Proizvodjac")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Lekovi");
                });

            modelBuilder.Entity("Models.Terapija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KartonPacijentaId")
                        .HasColumnType("int");

                    b.Property<int?>("LekId")
                        .HasColumnType("int");

                    b.Property<string>("Uputstvo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KartonPacijentaId");

                    b.HasIndex("LekId");

                    b.ToTable("Terapije");
                });

            modelBuilder.Entity("Models.KartonPacijenta", b =>
                {
                    b.HasOne("Models.KovidAmbulanta", "Ambulanta")
                        .WithMany("Kartoni")
                        .HasForeignKey("AmbulantaId");

                    b.Navigation("Ambulanta");
                });

            modelBuilder.Entity("Models.Terapija", b =>
                {
                    b.HasOne("Models.KartonPacijenta", "KartonPacijenta")
                        .WithMany("Terapije")
                        .HasForeignKey("KartonPacijentaId");

                    b.HasOne("Models.Lek", "Lek")
                        .WithMany()
                        .HasForeignKey("LekId");

                    b.Navigation("KartonPacijenta");

                    b.Navigation("Lek");
                });

            modelBuilder.Entity("Models.KartonPacijenta", b =>
                {
                    b.Navigation("Terapije");
                });

            modelBuilder.Entity("Models.KovidAmbulanta", b =>
                {
                    b.Navigation("Kartoni");
                });
#pragma warning restore 612, 618
        }
    }
}
